# Generated by Django 4.2.13 on 2026-04-11 13:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScanLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('sender', models.CharField(blank=True, default='', max_length=512)),
                ('recipient', models.CharField(blank=True, default='', max_length=512)),
                ('subject', models.CharField(blank=True, default='', max_length=998)),
                ('reply_to', models.CharField(blank=True, default='', max_length=512)),
                ('x_mailer', models.CharField(blank=True, default='', max_length=255)),
                ('email_date', models.CharField(blank=True, default='', max_length=128)),
                ('spf', models.CharField(blank=True, default='', max_length=128)),
                ('dkim', models.CharField(blank=True, default='', max_length=128)),
                ('dmarc', models.CharField(blank=True, default='', max_length=128)),
                ('domain_age', models.CharField(blank=True, default='', max_length=128)),
                ('ssl_status', models.CharField(blank=True, default='', max_length=128)),
                ('ip_address', models.CharField(blank=True, default='', max_length=128)),
                ('attachments', models.CharField(blank=True, default='', max_length=512)),
                ('label', models.CharField(choices=[('phishing', 'Phishing'), ('legitimate', 'Legitimate')], max_length=16)),
                ('confidence_score', models.FloatField()),
                ('metadata_json', models.TextField(default='{}')),
                ('explanation_json', models.TextField(default='[]')),
            ],
            options={
                'verbose_name': 'Scan Log',
                'verbose_name_plural': 'Scan Logs',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
